import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Film, Users, User } from 'lucide-react';
import SwipeDeck from './components/SwipeDeck';
import ProfileTab from './components/tabs/ProfileTab';
import RoomsTab from './components/tabs/RoomsTab';

// Temporary fixed testing IDs generated by our seedLobby script
const TEST_USER_ID = 'df538736-c846-49aa-b465-72d95d6b9001';
const TEST_ROOM_ID = 'c0cbd297-a961-425d-81fb-87439a24f8dd';

function App() {
  const [activeTab, setActiveTab] = useState('feed'); // 'profile', 'feed', 'rooms'
  const swipeDeckRef = useRef(null);
  const [queue, setQueue] = useState([]);
  const [lastAction, setLastAction] = useState(null);
  const [userProfile, setUserProfile] = useState(null);

  const currentUserId = userProfile ? userProfile.user_id : TEST_USER_ID;

  useEffect(() => {
    // 1. Initial Data Load - Fetch the real 100 movies from PostgreSQL
    const fetchQueue = async () => {
      try {
        const response = await fetch(`http://localhost:3000/api/queue/${currentUserId}/${TEST_ROOM_ID}`);
        if (!response.ok) throw new Error('Failed to fetch queue');
        const data = await response.json();
        setQueue(data.queue);
      } catch (error) {
        console.error('Error fetching movie queue:', error);
      }
    };
    fetchQueue();
  }, [currentUserId]);

  const handleSwipe = async (movie, action) => {
    setLastAction(`${action} on ${movie.title}`);

    // 2. Transmit the physical swipe logic directly to PostgreSQL
    try {
      await fetch('http://localhost:3000/api/swipes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: currentUserId,
          movieId: movie.movie_id,
          action: action
        })
      });
    } catch (error) {
      console.error('Error recording swipe:', error);
    }
  };

  return (
    <div className="flex flex-col items-center justify-between min-h-screen bg-slate-900 w-full overflow-hidden font-sans relative">
      <div className="absolute top-8 left-0 right-0 text-center z-50 pointer-events-none">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400 drop-shadow-lg tracking-tight">
          MovieMatch
        </h1>
        <p className="text-slate-400 font-medium text-sm mt-2 tracking-widest uppercase">
          Eliminate decision fatigue
        </p>
      </div>

      {/* Main Content Area */}
      <div className="relative mt-20 flex-1 w-full h-full z-40">
        <AnimatePresence mode="wait">
          {activeTab === 'profile' && (
            <motion.div key="profile" initial={{ opacity: 0, x: -50 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -50 }} className="absolute inset-0">
              <ProfileTab userProfile={userProfile} setUserProfile={setUserProfile} />
            </motion.div>
          )}

          {activeTab === 'rooms' && (
            <motion.div key="rooms" initial={{ opacity: 0, x: 50 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 50 }} className="absolute inset-0">
              <RoomsTab />
            </motion.div>
          )}

          {activeTab === 'feed' && (
            <motion.div key="feed" initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -50 }} className="absolute inset-0 flex flex-col items-center">
              <SwipeDeck ref={swipeDeckRef} queue={queue} onSwipe={handleSwipe} />

              <div className="relative mt-12 z-50 flex flex-col items-center gap-3 w-full">
                {lastAction && (
                  <div className="text-emerald-400 shadow-xl font-semibold text-lg bg-black/60 px-6 py-2 rounded-full backdrop-blur-md">
                    Last Action: {lastAction}
                  </div>
                )}
                <div className="flex items-center justify-center gap-[70px] text-xs text-slate-500 font-bold tracking-widest uppercase mb-6 bg-slate-900/40 p-3 rounded-full backdrop-blur-sm border border-white/5">
                  <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.8 }} onClick={() => swipeDeckRef.current?.swipe('LEFT')} className="flex flex-col items-center hover:text-red-400 transition-colors p-3 bg-red-500/10 rounded-full border border-red-500/20 shadow-[0_0_15px_rgba(239,68,68,0.1)]">
                    <span className="text-3xl drop-shadow-[0_0_10px_rgba(239,68,68,0.3)]">👎</span>
                  </motion.button>

                  <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.8 }} onClick={() => swipeDeckRef.current?.swipe('DOWN')} className="flex flex-col items-center hover:text-blue-400 transition-colors p-3 bg-blue-500/10 rounded-full border border-blue-500/20 shadow-[0_0_15px_rgba(59,130,246,0.1)]">
                    <span className="text-3xl drop-shadow-[0_0_10px_rgba(59,130,246,0.3)]">👇</span>
                  </motion.button>

                  <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.8 }} onClick={() => swipeDeckRef.current?.swipe('RIGHT')} className="flex flex-col items-center hover:text-green-400 transition-colors p-3 bg-green-500/10 rounded-full border border-green-500/20 shadow-[0_0_15px_rgba(34,197,94,0.1)]">
                    <span className="text-3xl drop-shadow-[0_0_10px_rgba(34,197,94,0.3)]">👍</span>
                  </motion.button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Bottom Floating Navigation Bar */}
      <div className="absolute bottom-8 z-50 flex gap-12 bg-slate-800/80 backdrop-blur-xl px-12 py-4 rounded-full border border-white/10 shadow-2xl items-center justify-between">
        <button onClick={() => setActiveTab('profile')} className={`flex flex-col items-center transition-colors ${activeTab === 'profile' ? 'text-emerald-400' : 'text-slate-500 hover:text-slate-300'}`}>
          <User size={28} />
        </button>

        <button onClick={() => setActiveTab('feed')} className={`flex flex-col items-center transition-colors -translate-y-4 bg-slate-800 p-4 rounded-full border border-white/10 shadow-lg ${activeTab === 'feed' ? 'text-blue-400 border-blue-400/30' : 'text-slate-400 hover:text-white'}`}>
          <Film size={34} />
        </button>

        <button onClick={() => setActiveTab('rooms')} className={`flex flex-col items-center transition-colors ${activeTab === 'rooms' ? 'text-emerald-400' : 'text-slate-500 hover:text-slate-300'}`}>
          <Users size={28} />
        </button>
      </div>

      {/* Background Decorators */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-emerald-600/10 rounded-full blur-[120px] pointer-events-none" />
    </div>
  );
}

export default App;
